(ns uml-viewer.application.ir-generator
  (:require [clojure.edn :as edn]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [uml-viewer.domain.policy :as policy]
            [uml-viewer.graph :as graph]))

(defn read-policy [path]
  (edn/read-string (slurp path)))

(defn emit [doc]
  (str ";; Generated by clj -M:ir from the policy file. Do not edit.\n"
       (binding [*print-namespace-maps* false
                 *print-length* nil
                 *print-level* nil
                 pprint/*print-right-margin* 90]
         (with-out-str (pprint/pprint doc)))))

(defn source-trees
  "Each source tree of `policy` as `{:lang :root :prefix :ns-prefix}`.
  `:prefix` is the policy prefix that `id-of` strips. A `:sources` entry's
  `:prefix` is that tree's namespace root."
  [policy]
  (let [prefix (or (:prefix policy) "uml-viewer")
        tree (fn [source]
               {:lang (keyword (or (:lang source) (:lang policy) :clojure))
                :root (or (:root source) (:src source) (:src policy) "src")
                :prefix prefix
                :ns-prefix (or (:prefix source) prefix)})]
    (if (seq (:sources policy))
      (mapv tree (:sources policy))
      [(tree {})])))

(defn- scan-tree [{:keys [lang root prefix ns-prefix]}]
  (let [impl (or (graph/lookup lang)
                 (throw (ex-info (str "no LanguageGraph for " lang) {:lang lang})))]
    (graph/scan impl root {:prefix prefix :ns-prefix ns-prefix :lang lang})))

(defn scan-policy
  "Scan `policy`. `:sources` merges one scanner per entry.
  Otherwise `graph-impl` scans `:src` with the policy prefix."
  [graph-impl policy]
  (if (seq (:sources policy))
    (graph/merge-scans (mapv scan-tree (source-trees policy)))
    (graph/scan graph-impl
                (or (:src policy) "src")
                {:prefix (or (:prefix policy) "uml-viewer")})))

(defn document
  "Scan source with `graph-impl` and apply `policy`. Returns the IR document.
  A policy with `:sources` selects each scanner itself."
  [graph-impl policy]
  (policy/apply-policy policy (scan-policy graph-impl policy)))

(defn generate
  "Write the IR document for `policy-path` using `graph-impl`. Returns the output path.
  A policy with `:sources` selects each scanner itself."
  ([graph-impl policy-path] (generate graph-impl policy-path nil))
  ([graph-impl policy-path out-path]
   (let [policy (read-policy policy-path)
         graph (scan-policy graph-impl policy)
         extra (policy/unassigned policy graph)
         doc (assoc (policy/apply-policy policy graph)
               :policy-file policy-path)
         out (or out-path (:out policy) "examples/uml-viewer.edn")]
     (when (seq extra)
       (binding [*out* *err*]
         (println "Unassigned namespaces:"
                  (str/join ", " (map :ns extra)))))
     (spit out (emit doc))
     out)))
